export const fakeData = [
     { id: 1, firstName: "ali", age: "20" },
     { id: 2, firstName: "amir", age: "23" },
     { id: 3, firstName: "hossein", age: "25" },
     { id: 4, firstName: "melika", age: "41" },
     { id: 5, firstName: "kamran", age: "14" },
     { id: 6, firstName: "zohre", age: "33" },
     { id: 7, firstName: "parisa", age: "7" },
     { id: 8, firstName: "mohammad", age: "17" },
     { id: 9, firstName: "pouya", age: "15" },
     { id: 10, firstName: "omid", age: "25" },
     { id: 11, firstName: "maryam", age: "30" },
     { id: 12, firstName: "armin", age: "71" },
     { id: 13, firstName: "leila", age: "41" },
     { id: 14, firstName: "atiye", age: "64" },
     { id: 15, firstName: "ahmad", age: "12" },
     { id: 16, firstName: "sahel", age: "9" },
     { id: 17, firstName: "majid", age: "13" },
     { id: 18, firstName: "mahmod", age: "21" },
     { id: 19, firstName: "sahar", age: "39" },
     { id: 20, firstName: "iman", age: "27" },
   ];